<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Title>KoiVM Watermark reader</Title>
    <Description>Reader of embedded watermark</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="dnlib" />
  </ItemGroup>
</Project>