<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>KoiVM Processor</Title>
    <Description>KoiVM distrbution processor</Description>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Confuser.Core" />
    <PackageReference Include="Confuser.DynCipher" />
    <PackageReference Include="Confuser.Protections" />
    <PackageReference Include="Confuser.Renamer" />
    <PackageReference Include="Confuser.Runtime" />
    <PackageReference Include="dnlib" />
  </ItemGroup>
</Project>